---
title: "Taller de an치lisis de datos I"
---

## Descripci칩n del curso

El procesamiento de datos se ha vuelto uno de los temas m치s importantes en la actualidad. Cada d칤a hay m치s profesionales que est치n optando por especializarse en la gesti칩n de informaci칩n para generar nuevo conocimiento y/u orientar la toma decisiones. En ese sentido, los datos han pasado a ser los protagonistas de nuestra 칠poca y es imprescindible desarrollar habilidades para comprender, procesar y analizar la informaci칩n que se encuentra disponible.

Una de las herramientas m치s 칰tiles para realizar estas tareas es R, un lenguaje y entorno de programaci칩n abierto para el procesamiento y an치lisis de datos en un sinn칰mero de disciplinas. La gran ventaja de esta herramienta, adem치s de ser gratuito, es su flexibilidad y versatilidad, ya que con 19000 librer칤as disponibles se puede realizar una amplia gama de tareas con datos de distinta naturaleza <https://cran.r-project.org/>.

Las clases estar치n programas de la siguiente manera:

|          |       Fecha        |    Horario    | Contenidos                     |                              Clase                              |                            Laboratorio                            |
|----------|:------------------:|:-------------:|--------------------------------|:---------------------------------------------------------------:|:-----------------------------------------------------------------:|
| Sesi칩n 1 | Viernes 13/05/2023 | 09:00 - 12:15 | Introducci칩n a `R` y `RStudio` | [游둰勇끃(class/class-1.html "Clase 1"){aria-label="Clase 1 slides"} | [游닄](labs/lab-1.html "Laboratorio 1"){aria-label="Laboratorio 1"} |
| Sesi칩n 2 | Viernes 27/05/2023 | 09:00 - 12:15 | Introducci칩n a `R` y `RStudio` | [游둰勇끃(class/class-1.html "Clase 1"){aria-label="Clase 1 slides"} | [游닄](labs/lab-1.html "Laboratorio 1"){aria-label="Laboratorio 1"} |
| Sesi칩n 3 | Viernes 01/07/2023 | 09:00 - 12:15 | Lectura y exploraci칩n de datos | [游둰勇끃(class/class2.html "Clase 1"){aria-label="Clase 2 slides"}  | [游닄](labs/lab-2.html "Laboratorio 2"){aria-label="Laboratorio 2"} |
| Sesi칩n 4 | S치bado 15/07/2023  | 09:00 - 12:15 | Manipulaci칩n de tablas         |                                                                 |                                                                   |
| Sesi칩n 5 | Viernes 02/09/2023 | 09:00 - 12:15 | Programaci칩n funcional I       |                                                                 |                                                                   |
| Sesi칩n 6 | Viernes 23/09/2023 | 09:00 - 12:15 | Programaci칩n funcional II      |                                                                 |                                                                   |
| Sesi칩n 7 | Viernes 04/11/2023 | 09:00 - 12:15 | Visualizaci칩n de datos         |                                                                 |                                                                   |
| Sesi칩n 8 | S치bado 18/11/2023  | 09:00 - 12:15 | Reporter칤a de datos            |                                                                 |                                                                   |

## Objetivos de aprendizaje

El objetivo de este taller es aplicar de manera pr치ctica a las principales herramientas que ofrece R para la lectura, procesamiento y visualizaci칩n de datos cuantitativos. Con esto se espera tener una base troncal para la exploraci칩n e implementaci칩n de cualquier otro an치lisis.

Al terminar el curso los estudiantes sabr치n:

1.  Realizar an치lsis exploratorio de datos en `R`.

2.  Generar visualizaciones de datos de calidad en `R` con `ggplot2`.

3.  Programar a un nivel b치sico-intermedio con estructuras de control, funciones y procesos iterativos.

Los puntos contenidos se realizar치n utilizando `R`, por lo que **los/as estudiantes profundizar치n su conocimiento de este lenguaje de programaci칩n**.

## Metodolog칤a del curso

El curso es pr치ctico por lo que tiene el prop칩sito de ense침ar a programar orientado a objetivos de investigaci칩n, por lo que tendremos actividades:

-   **Interactivas**: los estudiantes deber치n programar an치lisis a partir de una pregunta/objetivo de investigaci칩n

-   **Aplicaci칩n**: los estudiantes deber치n aplicar alguna de las t칠cnicas vistas a una pregunta **relevante para las pol칤ticas p칰blicas**

## Evaluaciones

El curso tendr치 4 Tareas, ponderadas con un 25% cada una y se realizar치n en parejas. Las tareas se organizaran de la siguiente manera:

|         | Fecha Publicaci칩n | Fecha - Horario de entrega | Contenidos                               |                     Pautas                      |                                                        Datos |
|---------|:-----------------:|:--------------------------:|------------------------------------------|:-----------------------------------------------:|-------------------------------------------------------------:|
| Tarea 1 |    01/07/2023     |     17/07/2023 - 23:59     | Vectores, matrices, listas y data frames | [Click aqu칤](/exams/Tarea1.pdf "Pauta Tarea 1") | [Click aqu칤](/exams/simce2m2016_extracto.csv "Data Tarea 1") |
| Tarea 2 |    16/07/2023     |     06/08/2023 - 23:59     | An치lisis descriptivo de datos            |                                                 |                                                              |
| Tarea 3 |    01/10/2023     |     22/10/2023 - 23:59     | Funciones y procesos iterativos          |                                                 |                                                              |
| Tarea 4 |    01/11/2023     |     19/11/2023 - 23:59     | Visualizaci칩n de datos                   |                                                 |                                                              |

**Todas las evaluaciones se deben enviar por correo al profesor Jos칠 Daniel Conejeros [jdconejeros\@uc.cl](jdconejeros@uc.cl) con copia a la ayudante Sof칤a Madariaga Alvarado [samadariaga\@uc.cl](samadariaga@uc.cl).**

**Nota:** Las parejas tienen que ser de 치reas distintas. Pueden cambiar las parejas a lo largo de las evaluaciones. Tambi칠n puede ser individual.

## Integridad acad칠mica

*Como miembro de la comunidad de la Pontificia Universidad Cat칩lica de Chile, me comprometo a respetar los principios y normativas que la rigen. Asimismo, me comprometo a actuar con rectitud y honestidad en las relaciones con los dem치s integrantes de la comunidad y en la realizaci칩n de todo trabajo, particularmente en aquellas actividades vinculadas a la docencia, al aprendizaje y la creaci칩n, difusi칩n y transferencia del conocimiento. Adem치s, me comprometo a velar por la dignidad e integridad de las personas, evitando incurrir en y, rechazando, toda conducta abusiva de car치cter f칤sico, verbal, psicol칩gico y de violencia sexual. Del mismo modo, asumo el compromiso de cuidar los bienes de la Universidad*.

M치s detalles sobre la integridad acad칠mica UC aqu칤: <https://integridadacademica.uc.cl/>

## Contribuciones y agradecimientos

El formato web de este curso fue desarrollado y adaptado a partir del trabajo de la Ph.D. [Mine 칂etinkaya-Rundel](https://mine-cr.com/) Profesora y Directora de Estudios de Grado del Departamento de Ciencias Estad칤sticas de la Universidad de Duke.

-   Puedes acceder al curso de referencia aqu칤: [STA 210](https://sta210-s22.github.io/website/)
