---
title: "Clase 1 y 2"
subtitle: "Introducción a R"
editor: visual
include-after-body: 
  - ../html/footer_post.html
---

::: {.callout-warning title="Ideas más importantes"}
1.  `R` es un lenguaje de programación de código orientado al análisis estadístico.

2.  `RStudio` es un entorno de desarrollo integrado para `R` que facilita el desarrollo de proyectos de ciencia de datos.

3.  La programación en `R` se orienta a la transformación de objetos a partir de funciones.
:::

## Presentación de la clase

<iframe src="/slides/TAD1_clase1.html" height="550" width="100%" allowfullscreen="true">

</iframe>

Puedes descargar la presentación en PDF dando [Click aquí](/slides/TAD1_clase1.pdf "Clase 1 pdf") ⏎

## Presentación de la clase

Puedes revisar el laboratorio dando [Click aquí](/labs/lab-1.qmd "Laboratorio 1") ⏎

También puedes descargar el proyecto directo para `RStudio` dando [Click aquí](/labs/TAD1_clase1_Taller.zip "Lab 1 zip") ⏎

## Literatura y enlaces de referencia

Wickham, H., & Grolemund, G. (2016). R for data science: import, tidy, transform, visualize, and model data. " O'Reilly Media, Inc.". Versión en español: <https://r4ds.hadley.nz/>

**Revisar el capítulo 1: Introducción**

<br><br>

::: {style="font-size: 0.875em;"}
Vuelve a la [descripción del curso](/ "Descripción del curso") ⏎
:::
